[metadata]
path = "/Siii/"
homepage = "http://example.com/Siii/"
title = "Siii Blog System"
subtitle = "A damn light-weight system implemented with PHP."
timezone = "Asia/Shanghai"
author = "Siii"
[metadata.license]
text = "Creative Commons BY-NC-SA 4.0"
link = "http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"

[cache]
enable = false
[cache.lifetime]
page = 43200  # 60 * 60 * 12 seconds
feed = 5400  # 60 * 60 * 1.5 seconds

[[timelines]]
name = "口水茶"
file = ["tweets/2013.txt", "tweets/2014.txt"]
[[timelines]]
name = "複製品"
file = ["clone.txt"]
[[timelines]]
name = "道德經"
file = "tao-te-ching.txt"
[[timelines]]
name = "關於"
file = "about.txt"
hidden = true  # hidden from homepage, not elsewhere (like feed.xml, categories, sitemap.xml)
