[metadata]
path = "/Siii/"
homepage = "http://www.example.com/Siii/"
title = "Siii Blog System"
subtitle = "A damn light-weight system implemented with PHP."
timezone = "Asia/Shanghai"
author = "Siii"
[metadata.license]
text = "Creative Commons BY-NC-SA 4.0"
link = "http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"

[cache]
enable = false
[cache.lifetime]
page = 43200  # 60 * 60 * 12 seconds
feed = 5400  # 60 * 60 * 1.5 seconds

[[timelines]]
name = "雑七雑八"
file = ["index.txt", "index.txt"]
[[timelines]]
name = "七雑八雑"
file = "test.txt"
[[timelines]]
name = "關於"
file = "about.txt"
hidden = true  # hidden from homepage, not elsewhere (like feed.xml, categories, sitemap.xml)
#[[timelines]]
#name = "日常生活"
#file = ["2013.txt", "2014.txt"]
#[[timelines]]
#name = "網絡風雲"
#file = "web.txt"
#[[timelines]]
#name = "遊戲世界"
#file = "game.txt"
